import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { Repository, portalSnapshot } from '../server/repository';
import { AppError, type Actor } from '../server/commands';
import type { SqlDatabase } from '../server/database';
import { dayOffset, loanCount, loanStatus } from '../app/domain';
import { receiptContent, type SignatureStrokes } from '../app/receipt-model';

export async function checkReceiptWorkflow(repo: Repository, db: SqlDatabase, owner: Actor, partner: Actor, merchantId: string, otherMerchantId: string) {
  let snapshot = await repo.read(owner);
  const execute = async (command: unknown) => { const result = await repo.execute(owner, crypto.randomUUID(), snapshot.revision, command); snapshot = result; return result; };
  const blankId = String((await execute({ kind: 'piece.save', piece: {} })).result!.id);
  const blank = snapshot.state.pieces.find(piece => piece.id === blankId)!;
  assert.match(blank.sku, /^ELO-\d{5}$/);
  assert.equal(blank.name, 'Peça ' + blank.sku);
  assert.deepEqual([blank.available, blank.minimum, blank.cost, blank.value], [0, 0, 0, 0]);
  const secondId = String((await execute({ kind: 'piece.save', piece: { name: 'Peça sem preço', available: 3 } })).result!.id);
  const second = snapshot.state.pieces.find(piece => piece.id === secondId)!;
  assert.notEqual(second.sku, blank.sku);
  await assert.rejects(execute({ kind: 'piece.save', piece: { sku: blank.sku.toLowerCase() } }), /cadastrado/);
  for (const piece of [{ available: -1 }, { value: -1 }, { cost: NaN }, { minimum: 1.2 }]) await assert.rejects(execute({ kind: 'piece.save', piece }));
  const loanId = String((await execute({ kind: 'loan.create', merchantId, items: { [secondId]: 2 }, due: dayOffset(2), notes: 'Retirada sem valor informado.' })).result!.id);
  const loan = snapshot.state.loans.find(value => value.id === loanId)!;
  assert.equal(loan.items[0].unitValue, 0);
  assert.equal(loanStatus(loan), 'Em andamento');
  const merchant = snapshot.state.merchants.find(value => value.id === merchantId)!;
  const content = receiptContent(loan, merchant, snapshot.state.settings!);
  const fingerprint = createHash('sha256').update(JSON.stringify(content)).digest('hex');
  const strokes: SignatureStrokes = [[[50, 250], [190, 110], [140, 300], [330, 150]], [[380, 200], [520, 220]]];
  const sign = { kind: 'loan.sign', loanId, signerName: 'Responsável no balcão', receiptFingerprint: fingerprint, strokes };
  for (const badStrokes of [[], [[[2, 2]]], [[[1, 1], [1, 1]]], [[[0, 0], [1001, 200]]], Array.from({ length: 6 }, () => Array.from({ length: 500 }, () => [0, 0]))]) await assert.rejects(execute({ ...sign, strokes: badStrokes }));
  await assert.rejects(execute({ ...sign, signerName: ' ' }));
  await assert.rejects(execute({ ...sign, receiptFingerprint: '0'.repeat(64) }), /mudou/);
  await assert.rejects(execute({ ...sign, signature: { at: '2000-01-01' } }), /Unrecognized/);
  await assert.rejects(repo.execute(partner, crypto.randomUUID(), snapshot.revision, sign), error => error instanceof AppError && error.status === 403);
  const beforeSign = await repo.read(owner);
  const id = crypto.randomUUID();
  snapshot = await repo.execute(owner, id, snapshot.revision, sign);
  const signed = snapshot.state.loans.find(value => value.id === loanId)!.receipt!;
  assert.ok(signed.signature.at.endsWith('Z'));
  assert.equal(signed.signature.name, sign.signerName);
  assert.deepEqual(signed.signature.strokes, strokes);
  assert.deepEqual(snapshot.state.notices, beforeSign.state.notices, 'Saving a signature must not queue a message');
  assert.equal(snapshot.state.loans.find(value => value.id === loanId)!.acknowledged, false);
  await repo.execute(owner, id, beforeSign.revision, sign);
  assert.equal((await repo.read(owner)).state.loans.find(value => value.id === loanId)!.events.filter(event => event.title === 'Comprovante assinado').length, 1);
  await assert.rejects(execute(sign), /já foi assinado/);
  const signedSnapshot = structuredClone(signed);
  const reloaded = await repo.read(owner);
  assert.deepEqual(reloaded.state.loans.find(value => value.id === loanId)!.receipt, signedSnapshot);
  const personal = portalSnapshot(await repo.read(partner));
  assert.deepEqual(personal.loans.find(value => value.id === loanId)!.receipt, signedSnapshot);
  assert.ok(personal.loans.every(value => value.merchantId !== otherMerchantId));
  // Editing the catalogue, recipient contact or assistance cannot rewrite a signed copy.
  await execute({ kind: 'piece.save', piece: { ...second, name: 'Nome alterado', value: 12500 } });
  await execute({ kind: 'merchant.save', merchant: { ...merchant, contact: 'Contato atualizado' } });
  await execute({ kind: 'settings.save', settings: { ...snapshot.state.settings, name: 'Assistência atualizada' } });
  const settle = { kind: 'loan.settle', loanId, productId: secondId, quantity: 1, action: 'sale' };
  const beforeRejectedSale = await repo.read(owner);
  await assert.rejects(execute(settle), /preço|valor/i);
  await assert.rejects(execute({ ...settle, saleUnitValue: 0 }));
  assert.deepEqual(await repo.read(owner), beforeRejectedSale);
  await execute({ ...settle, saleUnitValue: 7900 });
  assert.equal(snapshot.state.receivables.find(value => value.loanId === loanId)!.amount, 7900);
  await execute({ ...settle, action: 'return' });
  assert.equal(loanCount(snapshot.state.loans.find(value => value.id === loanId)!), 0);
  assert.deepEqual(snapshot.state.loans.find(value => value.id === loanId)!.receipt, signedSnapshot);
  await assert.rejects(db.prepare('UPDATE loan_items SET value=-1 WHERE loan_id=?').bind(loanId).run(), /check constraint/);
  // Even a known, already used command ID cannot grant write access through the portal.
  for (const command of [{ kind: 'portal.acknowledge', loanId }, { kind: 'portal.read' }, { kind: 'portal.dispute', loanId, reason: 'Test' }, { kind: 'portal.extend', loanId, date: dayOffset(3), reason: 'Test' }, { kind: 'portal.return', loanId, reason: 'Test' }]) await assert.rejects(repo.execute(partner, id, snapshot.revision, command), error => error instanceof AppError && error.status === 403);
  console.log('OK: optional piece fields/unique codes, unpriced loans, explicit sale price, read-only portal, signed snapshot persistence/isolation, stale/invalid/duplicate signature rejection and no message queued by signing.');
}
