'use client';
import {useEffect,useState} from 'react';
import {Copy,ExternalLink,Mail,ShieldCheck,Check,LoaderCircle} from 'lucide-react';
import {toast} from 'sonner';
import type {Messages} from './notifications';
export function GmailConnection({messages,onConnected}:{messages:Messages;onConnected:()=>void}){
 const prepared=messages.data.gmailSetup;const [sender,setSender]=useState(prepared?.sender||'idtech.assessoria@gmail.com');const [endpoint,setEndpoint]=useState(messages.data.connection.provider==='gmail'?messages.data.connection.endpoint||'':'');const [code,setCode]=useState('');const [copied,setCopied]=useState(false);const [loadingCode,setLoadingCode]=useState(false);
 useEffect(()=>{if(prepared?.sender)setSender(prepared.sender)},[prepared?.sender]);
 const ready=!!prepared?.prepared&&prepared.sender===sender.trim().toLowerCase();
 async function copyCode(){setLoadingCode(true);try{const r=await fetch('/api/messaging/gmail-code',{cache:'no-store'});const v=await r.json() as {script?:string;sender?:string;error?:string};if(!r.ok||!v.script||v.sender!==sender.trim().toLowerCase())throw Error(v.error||'Prepare a conexão para este Gmail primeiro.');setCode(v.script);try{await navigator.clipboard.writeText(v.script);setCopied(true);toast.success('Código copiado. Cole no seu projeto Google Apps Script.')}catch{toast.info('Selecione e copie o código exibido abaixo.')}}catch(e){toast.error((e as Error).message)}finally{setLoadingCode(false)}}
 return <div className="gmail-setup"><div className="gmail-setup-intro"><Mail size={24}/><div><strong>Use sua conta Gmail para enviar os avisos</strong><p>A configuração é feita uma vez na sua conta Google. Não exige domínio nem acesso à sua caixa de entrada.</p></div></div>
 <section className="gmail-step"><span className="gmail-step-number">1</span><div><h3>Prepare o código da conexão</h3><label className="field">Gmail da assistência<input type="email" value={sender} maxLength={150} onChange={e=>{setSender(e.target.value);setCode('');setCopied(false)}} placeholder="idtech.assessoria@gmail.com"/></label><div className="button-row">{!ready?<button className="btn primary" disabled={messages.busy||!messages.data.connection.encryptionReady||!sender.toLowerCase().endsWith('@gmail.com')} onClick={async()=>{if(await messages.action({kind:'gmail.prepare',sender:sender.trim()})){setCode('');setCopied(false);toast.success('Conexão preparada. Copie o código no próximo botão.')}}}><ShieldCheck size={16}/>Preparar conexão</button>:<button className="btn primary" disabled={loadingCode||messages.busy} onClick={()=>void copyCode()}>{loadingCode?<LoaderCircle className="spinning" size={16}/>:copied?<Check size={16}/>:<Copy size={16}/>}Copiar código da conexão</button>}</div><p className="small">O código é exclusivo da sua assistência. Cole somente no seu próprio projeto Google.</p>{code&&<details className="gmail-code"><summary>Ver código para copiar manualmente</summary><textarea readOnly rows={8} value={code} aria-label="Código da conexão Google Apps Script" onFocus={e=>e.target.select()}/></details>}</div></section>
 <section className="gmail-step"><span className="gmail-step-number">2</span><div><h3>Ative o envio na sua conta Google</h3><p>Abra o Google Apps Script com <strong>{sender}</strong> e siga estas etapas:</p><ol><li>Crie um <strong>Novo projeto</strong> e dê o nome <strong>Elo — IDTech</strong>.</li><li>No arquivo <strong>Código.gs</strong>, substitua o conteúdo pelo código copiado no passo 1 e salve.</li><li>Escolha <strong>Implantar → Nova implantação → Aplicativo da Web</strong>.</li><li>Em <strong>Executar como</strong>, selecione <strong>Eu ({sender})</strong>. Em <strong>Quem pode acessar</strong>, selecione <strong>Qualquer pessoa</strong>.</li><li>Clique em <strong>Implantar</strong>, autorize o envio na conta Google e copie a <strong>URL do aplicativo da Web</strong>, terminada em <strong>/exec</strong>.</li></ol><p className="small">A URL permite que o Elo envie pedidos ao Google. O código exige uma assinatura válida em cada pedido e confirma a conta remetente antes de enviar.</p><a href="https://script.google.com/home" target="_blank" rel="noreferrer" className="btn secondary">Abrir Google Apps Script <ExternalLink size={16}/></a></div></section>
 <section className="gmail-step"><span className="gmail-step-number">3</span><div><h3>Conclua a conexão no Elo</h3><form onSubmit={async e=>{e.preventDefault();if(await messages.action({kind:'gmail.connect',endpoint:endpoint.trim(),revision:messages.data.connection.revision})){setCode('');toast.success('Conta Gmail confirmada. Os próximos avisos poderão ser enviados por ela.');onConnected()}}}><label className="field">URL copiada no Google<input type="url" required value={endpoint} maxLength={500} onChange={e=>setEndpoint(e.target.value)} placeholder="https://script.google.com/macros/s/…/exec"/></label><button className="btn primary" type="submit" disabled={!ready||messages.busy||!endpoint.trim()}><ShieldCheck size={16}/>{messages.busy?'Verificando com o Google…':'Verificar conta e ativar'}</button></form><p className="small">A verificação não envia e-mail. Depois de conectar, você poderá enviar um teste para sua conta de acesso ao Elo. Avisos antigos aguardam revisão individual.</p></div></section>
 <div className="info-box"><Mail size={18}/><span>Contas Gmail pessoais têm limite de envio pelo Apps Script; a cota disponível será mostrada após conectar. O Elo confirma o envio pelo Google, mas esta conexão não informa entrega ou leitura. <a href="https://developers.google.com/apps-script/guides/services/quotas" target="_blank" rel="noreferrer">Consultar limites do Google</a>.</span></div>
 </div>;
}
