'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {Bell,Mail,MessageSquare,CheckCheck,ArrowRight,Copy,Settings2,RefreshCw,Send,CheckCircle2,TriangleAlert,Clock3,ExternalLink,Pause,Play,ShieldCheck,X,Search} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {toast} from 'sonner';
import {GmailConnection} from './gmail-connection';
import {type Notice,type State,dateLabel} from './domain';
import {type MessagingSnapshot,type EmailDelivery,emailStatus,whatsappPhone} from './messaging-types';
const initial:MessagingSnapshot={connection:{configured:false,enabled:false,sender:'',revision:0,verifiedAt:null,encryptionReady:false},deliveries:[]};
export function useMessaging(enabled:boolean,changed:string){
 const [data,setData]=useState<MessagingSnapshot>(initial);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const running=useRef(false);const testId=useRef('');const sequence=useRef(0);
 const refresh=useCallback(async()=>{if(running.current)return;const seq=++sequence.current;try{const r=await fetch('/api/messaging',{cache:'no-store'});const v=await r.json() as MessagingSnapshot&{error?:string};if(!r.ok)throw Error(v.error||'Não foi possível carregar os envios.');if(seq===sequence.current){setData(v);setError('')}}catch(e){if(seq===sequence.current)setError((e as Error).message)}finally{setLoading(false)}},[]);
 const action=useCallback(async(input:Record<string,unknown>,quiet=false)=>{if(running.current)return false;running.current=true;sequence.current++;if(!quiet)setBusy(true);if(input.kind==='test'){if(!testId.current)testId.current=crypto.randomUUID();input={...input,id:testId.current}}
  try{const r=await fetch('/api/messaging',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const v=await r.json() as MessagingSnapshot&{error?:string};if(!r.ok)throw Error(v.error||'Não foi possível concluir a solicitação.');setData(v);setError('');if(input.kind==='test')testId.current='';return true}catch(e){if(!quiet)toast.error((e as Error).message,{duration:7000});else setError((e as Error).message);return false}finally{running.current=false;if(!quiet)setBusy(false)}
 },[]);
 useEffect(()=>{if(enabled)void refresh()},[enabled,changed,refresh]);
 useEffect(()=>{if(!enabled)return;const tick=()=>{if(document.visibilityState==='visible')void action({kind:'process'},true)};const timer=setInterval(tick,30000);return()=>clearInterval(timer)},[enabled,action]);
 return {data,error,loading,busy,refresh,action};
}
export type Messages=ReturnType<typeof useMessaging>;
function Badge({row}:{row?:EmailDelivery}){const s=row?emailStatus[row.status]:null;return <span className={'badge '+(s?.tone||'neutral')}>{s?.label||'Aviso interno'}</span>}
const time=(v:string)=>new Date(v).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'});
export function NotificationsCenter({state,messages,openNotice,markRead}:{state:State;messages:Messages;openNotice:(notice:Notice)=>void;markRead:()=>void}){
 const [filter,setFilter]=useState('all');const [search,setSearch]=useState('');const [settings,setSettings]=useState(false);const {data,error,loading,busy,action}=messages;const c=data.connection;
 const noticeMap=new Map(data.deliveries.filter(d=>d.noticeId).map(d=>[d.noticeId,d]));
 const pending=data.deliveries.filter(d=>['awaiting_connection','missing_recipient','queued','sending'].includes(d.status));const problems=data.deliveries.filter(d=>['failed','uncertain','bounced','complained'].includes(d.status));
 const visible=state.notices.filter(n=>{const row=noticeMap.get(n.id);return (filter==='all'||filter==='owner'&&n.audience==='Você'||filter==='merchant'&&n.audience==='Lojista'||filter==='unread'&&!n.read||filter==='attention'&&row&&['failed','uncertain','bounced','complained','missing_recipient'].includes(row.status))&&`${n.title} ${n.loanId} ${state.merchants.find(m=>m.id===n.merchantId)?.name||''}`.toLowerCase().includes(search.toLowerCase())});
 return <>
  <div className="message-hero"><div><span className="eyebrow">COMUNICAÇÃO DA ASSISTÊNCIA</span><h2>Os dois lados, sempre informados.</h2><p>Cada empréstimo mantém seus avisos, destinatários e registros de envio juntos.</p></div><button className="btn primary" onClick={()=>setSettings(true)}><Settings2 size={17}/>Configurar e-mail</button></div>
  <div className="message-channels">
   <div className="message-channel"><span className="icon-tile"><Bell size={20}/></span><div><strong>Dentro do Elo</strong><p>Avisos para você e para o portal do lojista.</p><span className="badge green">Ativo</span></div></div>
   <div className="message-channel"><span className="icon-tile"><Mail size={20}/></span><div><strong>E-mail automático</strong><p>{loading?'Consultando conexão…':c.configured?c.sender:'Conecte o Gmail da assistência para começar.'}</p><span className={'badge '+(c.enabled?'green':'amber')}>{loading?'Consultando':c.enabled?'Conectado':c.configured?'Pausado':'Configurar remetente'}</span></div></div>
   <div className="message-channel"><span className="icon-tile"><MessageSquare size={20}/></span><div><strong>WhatsApp</strong><p>Mensagem completa, pronta para compartilhar.</p><span className="badge neutral">Envio confirmado por você</span></div></div>
  </div>
  <div className="message-stats"><span><b>{state.notices.filter(n=>!n.read).length}</b> avisos não lidos</span><span><b>{pending.length}</b> e-mails pendentes</span>{c.provider==='gmail'?<span><b>{data.deliveries.filter(d=>d.status==='sent').length}</b> envios pelo Gmail</span>:<span><b>{data.deliveries.filter(d=>d.status==='delivered').length}</b> entregas confirmadas</span>}<span className={problems.length?'text-red':''}><b>{problems.length}</b> precisam de atenção</span></div>
  {error&&<div className="info-box" role="alert"><TriangleAlert size={18}/><span>{error}</span><button className="text-button" onClick={()=>void messages.refresh()}>Tentar novamente</button></div>}
  <section className="panel"><div className="toolbar notification-toolbar"><Tabs value={filter} onValueChange={setFilter}><TabsList className="filter-tabs"><TabsTrigger value="all">Todos</TabsTrigger><TabsTrigger value="owner">Para você</TabsTrigger><TabsTrigger value="merchant">Lojistas</TabsTrigger><TabsTrigger value="unread">Não lidos</TabsTrigger><TabsTrigger value="attention">Atenção</TabsTrigger></TabsList></Tabs><button className="text-button" onClick={markRead}><CheckCheck size={16}/>Marcar como lidos</button></div><div className="notification-search"><Search size={17}/><input aria-label="Buscar avisos" placeholder="Buscar empréstimo, lojista ou assunto…" value={search} onChange={e=>setSearch(e.target.value)}/><button className="text-button" disabled={busy} onClick={async()=>{if(await action({kind:'process'}))toast.success('Fila de mensagens atualizada.')}}><RefreshCw size={15}/>Atualizar fila</button></div>
   <div className="notices-list">{visible.map(n=>{const row=noticeMap.get(n.id);return <button className={'notice-row '+(!n.read?'unread':'')} key={n.id} onClick={()=>openNotice(n)}><span className="notice-icon">{n.audience==='Você'?<Bell size={21}/>:<MessageSquare size={21}/>}</span><span className="notice-main"><span className="chip-row"><strong>{n.title}</strong><span className="badge neutral">{n.audience==='Você'?'Para você':state.merchants.find(m=>m.id===n.merchantId)?.name}</span></span><span>{n.loanId} · {row?.recipient||'E-mail não cadastrado'}</span><small>{n.audience==='Você'?'Disponível na sua central':n.portalRead?'Visualizado pelo lojista no portal':'Aguardando leitura no portal'}{row?.whatsappAt?' · WhatsApp preparado':''}</small></span><span className="notice-end"><Badge row={row}/><time>{dateLabel(n.at)}</time><ArrowRight size={16}/></span></button>})}</div>
   {!visible.length&&<div className="empty-state"><Bell size={30}/><h3>{search||filter!=='all'?'Nenhum aviso neste filtro':'Sua comunicação começa na primeira retirada'}</h3><p>{search||filter!=='all'?'Ajuste a busca ou escolha outro filtro.':'Ao registrar um empréstimo, o Elo cria um aviso para você e outro para o lojista.'}</p></div>}
  </section>
  <div className="notification-footnote"><Clock3 size={16}/><p>Vencimentos são conferidos ao abrir o painel. A fila de e-mails avança nas operações e a cada 30 segundos enquanto o painel está visível. O agendamento com o sistema fechado ainda não está ativo.</p></div>
  <ConnectionDialog open={settings} onClose={()=>setSettings(false)} messages={messages}/>
 </>;
}
function ConnectionDialog({open,onClose,messages}:{open:boolean;onClose:()=>void;messages:Messages}){
 const c=messages.data.connection;const [sender,setSender]=useState(c.sender);const [apiKey,setApiKey]=useState('');const [edit,setEdit]=useState(!c.configured);const [provider,setProvider]=useState<string>(c.provider||'gmail');
 useEffect(()=>{if(open){setSender(c.provider==='resend'?c.sender:'');setApiKey('');setEdit(!c.configured);setProvider(c.provider||'gmail')}else setApiKey('')},[open,c.sender,c.configured,c.provider]);
 const tests=messages.data.deliveries.filter(d=>!d.noticeId).slice(0,3);
 return <Dialog open={open} onOpenChange={o=>{if(!o)onClose()}}><DialogContent className="elo-dialog connection-dialog"><DialogHeader><span className="eyebrow">CANAIS DE ENVIO</span><DialogTitle>{c.configured&&!edit?'Seu e-mail de envio':'Conectar o e-mail da assistência'}</DialogTitle><DialogDescription>Avisos para você e para o lojista nas próximas operações.</DialogDescription></DialogHeader><div className="dialog-body">
  {c.configured&&!edit?<><div className="connection-ready"><ShieldCheck size={27}/><div><strong>{c.sender}</strong><p>{c.provider==='gmail'?'Gmail autorizado':'Domínio verificado'} em {c.verifiedAt?time(c.verifiedAt):'—'}.</p></div></div>{c.provider==='gmail'&&<p className="small">Última cota informada pelo Google: <strong>{c.quotaRemaining??'—'} destinatários</strong>. A cota pode ser compartilhada com outros scripts da conta. A conexão confirma envio; entrega e leitura não são informadas.</p>}<label className="setting-row"><span><strong>Enviar e-mails nas próximas operações</strong><small>Avisos anteriores aguardam sua revisão individual.</small></span><Switch checked={c.enabled} disabled={messages.busy} onCheckedChange={async enabled=>{await messages.action({kind:'pause',enabled,revision:c.revision})}}/></label><div className="button-row"><button className="btn secondary" disabled={messages.busy||!c.enabled} onClick={async()=>{if(await messages.action({kind:'test'}))toast.success('Teste registrado para o e-mail da sua conta de acesso ao Elo. Confira o status abaixo.')}}><Send size={16}/>Enviar teste para mim</button><button className="text-button" onClick={()=>setEdit(true)}>Alterar conexão</button></div></>:<>
   <Tabs value={provider} onValueChange={setProvider}><TabsList className="filter-tabs"><TabsTrigger value="gmail">Gmail · sem domínio</TabsTrigger><TabsTrigger value="resend">Resend · domínio próprio</TabsTrigger></TabsList></Tabs>
   {provider==='gmail'?<GmailConnection messages={messages} onConnected={()=>setEdit(false)}/>:<form onSubmit={async e=>{e.preventDefault();if(await messages.action({kind:'configure',sender,revision:c.revision,...(apiKey?{apiKey}:{})})){setApiKey('');setEdit(false);toast.success('Domínio verificado. E-mail conectado para as próximas operações.')}}}>
    <div className="info-box"><Mail size={18}/><span>Use um remetente do seu domínio verificado no Resend. Para usar @gmail.com, selecione a opção Gmail acima.</span></div>
    <label className="field">E-mail que enviará os avisos *<input type="email" autoComplete="email" value={sender} onChange={e=>setSender(e.target.value)} required maxLength={150} placeholder="avisos@suaassistencia.com.br"/></label>
    <label className="field">Chave de API do Resend {c.configured&&c.provider==='resend'?'(opcional para manter a atual)':'*'}<input type="password" autoComplete="new-password" value={apiKey} onChange={e=>setApiKey(e.target.value)} required={!c.configured||c.provider!=='resend'} maxLength={220} placeholder={c.configured&&c.provider==='resend'?'Deixe vazio para manter a credencial':'re_…'}/><small>Use acesso completo para validar o domínio e consultar entregas. A chave é protegida no servidor.</small></label>
    <button className="btn primary" disabled={messages.busy||!c.encryptionReady} type="submit"><ShieldCheck size={16}/>{messages.busy?'Validando conexão…':'Verificar e conectar'}</button>
    <div className="connection-links"><a href="https://resend.com/domains" target="_blank" rel="noreferrer">Ver meus domínios <ExternalLink size={13}/></a><a href="https://resend.com/api-keys" target="_blank" rel="noreferrer">Gerenciar chaves no Resend <ExternalLink size={13}/></a></div>
   </form>}
   {c.configured&&<button type="button" className="text-button" onClick={()=>{setEdit(false);setApiKey('')}}>Manter a conexão atual</button>}
  </>}
  {!!tests.length&&<div className="message-tests"><h3>Últimos testes</h3>{tests.map(t=><div key={t.id}><span><strong>{t.recipient}</strong><small>{time(t.createdAt)}{t.error?' · '+t.error:''}</small></span><Badge row={t}/>{t.providerId&&t.provider!=='gmail'&&<button className="icon-button" title="Consultar entrega do teste" aria-label="Consultar entrega do teste" disabled={messages.busy} onClick={()=>void messages.action({kind:'check',id:t.id})}><RefreshCw size={15}/></button>}</div>)}</div>}
  <div className="info-box"><MessageSquare size={18}/><span>No WhatsApp, abra um aviso para revisar o texto e confirmar o envio no aplicativo. A automação por WhatsApp Business ainda precisa ser conectada.</span></div>
 </div><div className="dialog-footer"><button className="btn secondary" onClick={onClose}>Concluir</button></div></DialogContent></Dialog>;
}
export function NoticeDialog({notice,state,messages,onClose,openLoan}:{notice:Notice|null;state:State;messages:Messages;onClose:()=>void;openLoan:(id:string)=>void}){
 const row=messages.data.deliveries.find(d=>d.noticeId===notice?.id);const [draft,setDraft]=useState('');const [ready,setReady]=useState(false);const [confirmSend,setConfirmSend]=useState(false);const [cancelConfirm,setCancelConfirm]=useState(false);
 const portalLink=typeof window!=='undefined'?window.location.origin+(notice?.audience==='Lojista'?'/portal':'/'):'';
 useEffect(()=>{setDraft((notice?.body||'')+'\n\nAcompanhar no Elo: '+portalLink);setReady(false);setConfirmSend(false);setCancelConfirm(false)},[notice?.id,portalLink]);
 const name=notice?.audience==='Você'?'você':state.merchants.find(m=>m.id===notice?.merchantId)?.name;const phone=whatsappPhone(row?.phone||'');const editable=!!row&&row.attempts===0&&['missing_recipient','awaiting_connection'].includes(row.status);
 return <Dialog open={!!notice} onOpenChange={o=>{if(!o)onClose()}}><DialogContent className="elo-dialog message-detail"><DialogHeader><DialogTitle>{notice?.title}</DialogTitle><DialogDescription>{notice?.loanId} · Aviso para {name}</DialogDescription></DialogHeader><div className="dialog-body">
  <div className="message-delivery-status"><div><span className="icon-tile"><Mail size={19}/></span><div><strong>{row?.recipient||'E-mail não cadastrado'}</strong><small>{row?.recipientName||name}</small></div></div><Badge row={row}/></div>
  {row&&<><p className="small">{emailStatus[row.status].help}</p>{row.error&&<div className="info-box" role="status"><TriangleAlert size={17}/><span>{row.error}</span></div>}<dl className="delivery-facts"><div><dt>Criado</dt><dd>{time(row.createdAt)}</dd></div><div><dt>Tentativas</dt><dd>{row.attempts}</dd></div><div><dt>Última alteração</dt><dd>{time(row.updatedAt)}</dd></div><div><dt>Leitura no portal</dt><dd>{notice?.audience==='Você'?'Aviso da assistência':state.notices.find(n=>n.id===notice?.id)?.portalRead?'Visualizado':'Não confirmada'}</dd></div></dl>
   <div className="button-row message-actions">{row.providerId&&row.provider!=='gmail'&&<button className="btn secondary" disabled={messages.busy} onClick={async()=>{if(await messages.action({kind:'check',id:row.id}))toast.success('Status consultado no serviço de e-mail.')}}><RefreshCw size={15}/>Consultar entrega</button>}{!row.providerId&&['awaiting_connection','failed'].includes(row.status)&&<button className="btn primary" disabled={messages.busy||!messages.data.connection.enabled} onClick={()=>setConfirmSend(true)}><Send size={15}/>{row.attempts?'Tentar novamente':'Enviar por e-mail'}</button>}{editable&&<button className="text-button" disabled={messages.busy} onClick={async()=>{if(await messages.action({kind:'recipient',id:row.id}))toast.success('Contato atualizado a partir do cadastro. Confira o endereço antes de enviar.')}}>Atualizar contato</button>}{row.attempts===0&&['awaiting_connection','missing_recipient','queued'].includes(row.status)&&<button className="text-button" disabled={messages.busy} onClick={()=>setCancelConfirm(true)}>Cancelar e-mail</button>}</div>
   {confirmSend&&<div className="message-confirm"><strong>Enviar este aviso para {row.recipient}?</strong><p>O e-mail usará o texto original registrado abaixo.</p><div className="button-row"><button className="btn primary" disabled={messages.busy} onClick={async()=>{if(await messages.action({kind:'send',id:row.id})){setConfirmSend(false);toast.success('Solicitação registrada. Acompanhe o status do e-mail.')}}}>Confirmar envio</button><button className="btn secondary" onClick={()=>setConfirmSend(false)}>Voltar</button></div></div>}
   {cancelConfirm&&<div className="message-confirm"><strong>Cancelar o envio deste e-mail?</strong><p>O aviso interno e seu histórico serão mantidos.</p><div className="button-row"><button className="btn secondary" disabled={messages.busy} onClick={async()=>{if(await messages.action({kind:'cancel',id:row.id}))setCancelConfirm(false)}}>Confirmar cancelamento</button><button className="text-button" onClick={()=>setCancelConfirm(false)}>Voltar</button></div></div>}
  </>}
  <details className="message-original" open><summary>Mensagem original do empréstimo</summary><pre className="notice-body">{notice?.body}</pre></details>
  <div className="whatsapp-composer"><h3><MessageSquare size={19}/>Compartilhar no WhatsApp</h3><p>Revise o texto. O envio será confirmado por você dentro do WhatsApp.</p><label className="field">Mensagem<textarea rows={6} value={draft} maxLength={20000} onChange={e=>{setDraft(e.target.value);setReady(false)}}/></label><div className="button-row"><button className="btn secondary" onClick={async()=>{try{await navigator.clipboard.writeText(draft);toast.success('Mensagem copiada.')}catch{toast.error('Selecione o texto para copiar.')}}}><Copy size={15}/>Copiar texto</button>{phone&&row&&draft.length<=6000&&(ready?<a className="btn primary" href={'https://wa.me/'+phone+'?text='+encodeURIComponent(draft)} target="_blank" rel="noreferrer">Abrir WhatsApp <ExternalLink size={15}/></a>:<button className="btn primary" disabled={messages.busy||!draft.trim()} onClick={async()=>{if(await messages.action({kind:'whatsapp',id:row.id}))setReady(true)}}><MessageSquare size={15}/>Preparar para {row.phone}</button>)}</div><small>{!phone?'Cadastre o WhatsApp no contato do destinatário e atualize o contato do aviso.':draft.length>6000?'Texto longo: copie a mensagem e cole no WhatsApp.':row?.whatsappAt?'Texto preparado em '+time(row.whatsappAt)+'. O envio e a leitura no WhatsApp não são confirmados pelo Elo.':'O histórico registra a preparação da mensagem. A entrega depende da sua confirmação no WhatsApp.'}</small></div>
 </div><div className="dialog-footer"><button className="btn secondary" onClick={onClose}>Fechar</button><button className="btn primary" onClick={()=>{if(notice)openLoan(notice.loanId);onClose()}}>Abrir empréstimo <ArrowRight size={16}/></button></div></DialogContent></Dialog>;
}
