"use client";
import {Box,ArrowLeftRight,Store,Bell,ShieldCheck,ScanLine,ClipboardCheck,Wallet,MessageSquare,Check,CheckCheck,Layers,ArrowUpRight,LockKeyhole,Database,PackageCheck,TriangleAlert} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
const modules=[
 {icon:Box,title:'Estoque que acompanha a peça',tag:'Operação',text:'Cadastro por SKU, modelo compatível, marca, qualidade, cor, lote e localização. Original, retirada e paralela são variantes distintas.',items:['Entradas, inventário físico e ajuste com motivo','Disponível, reservado, emprestado e quarentena separados','Custo, valor de reposição e estoque mínimo','Fotos, número de série e leitura de QR ou código de barras']},
 {icon:ArrowLeftRight,title:'Empréstimo com começo e fim',tag:'Núcleo',text:'Uma retirada pode conter várias peças e quantidades. Cada item mantém seu próprio saldo e o valor combinado no momento da entrega.',items:['Conferência na saída e prazo combinado','Aceite ou contestação pelo lojista','Devolução parcial com inspeção e fotos','Uso, venda, dano, perda e cancelamento com tratamento próprio']},
 {icon:Store,title:'Relacionamento com lojistas',tag:'Parcerias',text:'Cada parceiro tem contatos, responsável, regras e um extrato transparente. Atrasos aparecem com seu contexto.',items:['Limite de exposição e prazo padrão por lojista','Empréstimos abertos e valores a receber juntos','Bloqueio manual com justificativa e revisão','Histórico de pontualidade com critérios visíveis']},
 {icon:Bell,title:'Avisos para os dois lados',tag:'Comunicação',text:'Você e o lojista recebem informações específicas para cada evento. Todos os avisos ficam associados ao empréstimo.',items:['WhatsApp e e-mail, conforme preferência e conexão','Retirada, aceite, vencimento e devolução','Fila de envio, tentativas e falhas visíveis','Confirmação de entrega separada do aceite da peça']},
 {icon:Wallet,title:'Peça usada vira valor a receber',tag:'Financeiro',text:'Quando o lojista fica com a peça, o saldo físico é resolvido e nasce uma pendência financeira. Criar a cobrança não significa receber.',items:['Conversão por item e quantidade','Pagamento parcial, desconto autorizado e estorno','Recibo, extrato do parceiro e conciliação','Caução, abatimento e compensação com aprovação']},
 {icon:ShieldCheck,title:'Controle sem complicar o balcão',tag:'Gestão',text:'A equipe vê apenas o que precisa para trabalhar. A gestão acompanha quem alterou cada registro e por quê.',items:['Dono, gerente, atendente e acesso do lojista','Histórico de eventos sem apagar movimentos antigos','Separação dos dados de cada assistência','Exportação, cópias de segurança e restauração verificada']}
];
const rules=[
 ['Estoque nunca fica negativo','A quantidade disponível é validada no servidor no momento da confirmação. Duas pessoas tentando emprestar a última unidade não podem gerar duas saídas. Reserva tem validade e é liberada ao expirar.'],
 ['Compatibilidade não é identidade','Uma tag compatível com iPhone 15 e 15 Plus é um único SKU com dois modelos compatíveis. Peças de qualidade, cor, lote ou procedência diferentes mantêm variantes próprias. Nenhuma associação acontece só pela semelhança do nome.'],
 ['Devolução parcial resolve somente o que voltou','A cada item: quantidade inicial = pendente + devolvida + convertida em venda + perda resolvida. Uma peça que volta com suspeita de defeito entra em quarentena, sem aumentar o disponível. Uma substituição precisa de um novo movimento vinculado.'],
 ['O combinado permanece no comprovante','Nome, SKU, qualidade, quantidade, preço de referência, prazo e condições são preservados no registro de saída. Editar o catálogo não reescreve o histórico. Alterar um acordo exige nova versão e aviso aos dois lados.'],
 ['Aceite precisa de uma ação do lojista','Envio, entrega e leitura de uma mensagem não confirmam o recebimento físico. O lojista confirma os itens ou abre uma divergência no portal. O registro mantém identidade, data, versão aceita e resultado.'],
 ['Prorrogação precisa de acordo','O lojista solicita uma data e um motivo; a assistência aprova ou recusa. Até a aprovação, o prazo original continua valendo. O histórico mantém as duas datas e os avisos correspondentes.'],
 ['Limite acompanha toda a exposição','O limite soma o valor das peças pendentes e os valores ainda a receber. Converter em venda não libera o limite. Um pagamento confirmado ou uma devolução reduz a exposição. Exceções exigem permissão e justificativa.'],
 ['Cancelamento não apaga uma retirada','Antes da entrega, cancelar libera a reserva. Depois da entrega, é necessário registrar a devolução ou o destino dos itens. Eventos de correção e estorno preservam a trilha original.'],
 ['Avisos são rastreáveis e não se repetem por acidente','Cada evento cria uma entrega por destinatário e canal. Repetir uma requisição não duplica a saída nem o aviso. Falhas entram em uma fila com tentativas limitadas, intervalo e ação manual.'],
 ['Avaria e perda passam por conferência','Fotos e relato ficam associados ao item. A assistência decide entre reparo, devolução ao estoque, baixa ou valor a receber. O sistema não acusa, cobra ou desconta automaticamente sem uma regra previamente acordada.']
];
const notifications=[
 ['Retirada registrada','Comprovante, lista das peças, valores, data, prazo e botão de confirmar recebimento.','Registro da saída, responsável e aceite pendente.'],
 ['Recebimento ou divergência','Confirmação do aceite ou protocolo da contestação.','Quem confirmou; itens aceitos ou divergência para resolver.'],
 ['Antes do prazo','Lembrete 24 horas antes, com saldo e opções de devolver ou pedir mais prazo.','Resumo diário das devoluções previstas.'],
 ['No vencimento e após','Aviso no vencimento; depois, lembrete conforme frequência acordada.','Pendências, dias de atraso e valor exposto por lojista.'],
 ['Devolução parcial ou total','Itens conferidos, condição, saldo restante e comprovante atualizado.','Movimento de entrada, quarentena e pendências.'],
 ['Venda ou pagamento','Valor combinado, vencimento financeiro e recibo após confirmação.','Conta a receber criada ou recebimento confirmado.']
];
export default function Scope(){return <div className="scope-page">
 <div className="scope-intro"><div><span className="eyebrow">O PROJETO POR INTEIRO</span><h2>Uma peça. Um responsável.<br/>Todo o caminho registrado.</h2><p>O Elo conecta o estoque da assistência aos lojistas parceiros, da retirada à devolução ou ao pagamento. Operação simples no balcão, controle completo por trás.</p></div><div className="scope-promise"><Layers size={27}/><strong>Construção em andamento</strong><span>A base de operação foi construída. Esta área acompanha os recursos entregues e os próximos módulos.</span><span className="badge lime">Base operacional construída</span></div></div>
 <Tabs defaultValue="product" className="scope-tabs"><TabsList className="wide-tabs"><TabsTrigger value="product">O sistema</TabsTrigger><TabsTrigger value="rules">Fluxo e regras</TabsTrigger><TabsTrigger value="notices">Avisos e portal</TabsTrigger><TabsTrigger value="delivery">Plano de entrega</TabsTrigger></TabsList>
 <TabsContent value="product"><div className="section-intro"><h3>Completo onde faz diferença.</h3><p>Seis frentes conectadas pela mesma movimentação de peça.</p></div><div className="scope-grid">{modules.map(m=><article className="panel scope-module" key={m.title}><div className="split"><span className="icon-tile"><m.icon size={23}/></span><span className="tiny-label">{m.tag}</span></div><h3>{m.title}</h3><p>{m.text}</p><ul>{m.items.map(i=><li key={i}><Check size={15}/>{i}</li>)}</ul></article>)}</div><div className="panel advantage"><ScanLine/><div><h3>Uma retirada rápida, um registro completo.</h3><p>Selecionar o lojista → ler ou escolher as peças → conferir o prazo e as condições → registrar. O estoque, o comprovante, o portal e os avisos usam o mesmo registro.</p></div></div><div className="scope-grid two"><article className="panel scope-module"><h3>Visão da assistência</h3><p>Disponibilidade real, peças com terceiros, quem deve devolver hoje, quanto está exposto e qual pendência precisa de ação.</p><div className="chip-row"><span className="badge neutral">Dono</span><span className="badge neutral">Gerente</span><span className="badge neutral">Atendente</span></div></article><article className="panel scope-module"><h3>Visão do lojista</h3><p>Somente seus empréstimos, com comprovantes, saldos e prazos. Pode confirmar recebimento, contestar, solicitar devolução e pedir prorrogação.</p><div className="chip-row"><span className="badge neutral">Acesso individual</span><span className="badge neutral">Próprios registros</span></div></article></div></TabsContent>
 <TabsContent value="rules"><div className="section-intro"><h3>O ciclo da peça</h3><p>O empréstimo tem um estado geral. Cada item conserva seu próprio saldo.</p></div><div className="flow-grid">{[{icon:Box,title:'Disponível',text:'Peça cadastrada e conferida no estoque.'},{icon:ClipboardCheck,title:'Retirada registrada',text:'Saída, prazo, condições e comprovante.'},{icon:Store,title:'Com o lojista',text:'Aceite, acompanhamento e avisos.'},{icon:PackageCheck,title:'Conferência de retorno',text:'Devolvida, usada ou com ocorrência.'}].map((f,i)=><article className="panel flow-step" key={f.title}><f.icon size={24}/><h3>{f.title}</h3><p>{f.text}</p>{i<3&&<ArrowUpRight size={18} className="flow-arrow"/>}</article>)}</div><div className="outcomes"><span><CheckCheck size={18}/> Devolvida → estoque</span><span><TriangleAlert size={18}/> Avariada → quarentena</span><span><Wallet size={18}/> Utilizada → valor a receber</span></div><div className="panel rule-panel"><h3>Regras que tornam o controle confiável</h3><Accordion type="multiple">{rules.map(([t,b],i)=><AccordionItem value={String(i)} key={t}><AccordionTrigger>{t}</AccordionTrigger><AccordionContent>{b}</AccordionContent></AccordionItem>)}</Accordion></div><div className="panel data-map"><Database/><div><h3>Registros que precisam existir</h3><p>Assistência, usuários e permissões · lojistas e contatos · peças e variantes · lotes e unidades · posições de estoque · empréstimos e itens · movimentos · aceites e divergências · prorrogações · contas e pagamentos · anexos · notificações e tentativas · histórico de auditoria.</p></div></div></TabsContent>
 <TabsContent value="notices"><div className="section-intro"><h3>Os dois lados sempre sabem o que aconteceu.</h3><p>A mesma operação gera mensagens adequadas para você e para o lojista.</p></div><div className="panel notification-matrix"><div className="matrix-head"><strong>Quando</strong><strong>O lojista recebe</strong><strong>Você recebe</strong></div>{notifications.map(([a,b,c])=><div className="matrix-row" key={a}><strong>{a}</strong><p>{b}</p><p>{c}</p></div>)}</div><div className="scope-grid two"><article className="panel scope-module"><span className="icon-tile"><MessageSquare/></span><h3>Uma mensagem útil de verdade</h3><div className="message-sample">Olá, Rafael. Você recebeu 2 telas iPhone 13 da Minha assistência.<br/><br/>Empréstimo: EMP-0248<br/>Quantidade: 2 · OLED premium<br/>Valor de referência: R$ 580,00<br/>Devolução: prazo combinado<br/><br/>Confira os itens e confirme o recebimento no seu portal.</div><p className="small">Exemplo de conteúdo. A mensagem completa inclui todos os itens, condições e saldo.</p></article><article className="panel scope-module"><span className="icon-tile"><LockKeyhole/></span><h3>Portal com acesso individual</h3><p>Portal protegido por autenticação e autorização por lojista. O contato de um parceiro nunca permite consultar outro.</p><ul><li><Check size={15}/>Confirmar ou contestar os itens</li><li><Check size={15}/>Ver comprovante e saldo atualizado</li><li><Check size={15}/>Solicitar prazo ou avisar que vai devolver</li><li><Check size={15}/>Informar uso de uma peça</li></ul><div className="info-box">Informar a devolução pelo portal não repõe o estoque. A entrada só acontece após a conferência da assistência.</div></article></div><div className="panel scope-module"><h3>O que precisa ser conectado para enviar de verdade</h3><p>A central inclui conexão Gmail sem domínio, integração Resend, fila persistente e tentativas protegidas. No Gmail, a assistência autoriza seu próprio projeto Google Apps Script e o Elo confirma o envio. O Resend exige domínio verificado e também permite consultar a entrega. WhatsApp Business automático e lembretes em segundo plano permanecem como próximas conexões.</p><div className="chip-row"><span className="badge neutral">Horário de Brasília</span><span className="badge neutral">Sem duplicação</span><span className="badge neutral">Reenvio controlado</span><span className="badge neutral">Entrega rastreável</span></div><p className="small">Os avisos são salvos para a assistência e para o portal do lojista. E-mail com fila persistente: conecte o Gmail sem domínio pelo Google Apps Script, ou use um remetente verificado no Resend. Gmail confirma envio; a consulta de entrega está disponível pelo Resend. O WhatsApp prepara o texto para confirmação no aplicativo. O agendamento fora do painel ainda não está ativo.</p></div></TabsContent>
 <TabsContent value="delivery"><div className="section-intro"><h3>Da proposta à operação real.</h3><p>Cada etapa tem uma entrega verificável. A complexidade entra no sistema, não na rotina da equipe.</p></div><div className="delivery-list">
 <article className="panel delivery-card current"><span className="delivery-icon"><Layers/></span><div><div className="chip-row"><h3>Estoque, empréstimos e financeiro</h3><span className="badge lime">Disponível aqui</span></div><p>Dados permanentes, cadastro e edição de peças e parceiros, limite por lojista, empréstimos com vários itens, devolução parcial, quarentena, conferência física, venda, pagamento parcial e estorno de registro.</p><strong>Como avaliar</strong><p>Cadastre uma peça e um parceiro, registre uma retirada, devolva uma unidade e confira os saldos. Após publicar esta etapa, os registros permanecem entre acessos. O estoque real começa vazio.</p></div></article>
 <article className="panel delivery-card"><span className="delivery-icon"><Database/></span><div><div className="chip-row"><h3>Acesso, histórico e saldos protegidos</h3><span className="badge lime">Construído</span></div><p>Login pela conta autorizada no Site, gestão exclusiva da proprietária, histórico com responsável, atualização conjunta dos registros, proteção contra retiradas simultâneas e gravações repetidas, exportação dos registros.</p><strong>Critério de aceite</strong><p>Persistência após recarregar; acesso negado a outro usuário; somente uma de duas retiradas simultâneas da última peça é aceita; repetir uma gravação não duplica a operação. Restauração de cópias e permissões de equipe seguem como módulos posteriores.</p></div></article>
 <article className="panel delivery-card"><span className="delivery-icon"><Bell/></span><div><div className="chip-row"><h3>Portal do lojista e comunicação</h3><span className="badge amber">Portal e central construídos</span></div><p>Portal individual pelo e-mail autorizado, confirmação do recebimento pelo próprio lojista, divergências, pedidos de prazo, aviso de devolução e extrato. Os avisos ficam salvos para os dois lados. E-mail automático disponível após conectar o Gmail ou configurar um remetente Resend; WhatsApp com revisão e envio pelo aplicativo. O agendamento em segundo plano ainda não está ativo.</p><strong>Critério de aceite</strong><p>Após habilitar o portal para um contato real, esse lojista vê apenas seus registros e confirma seus próprios itens. Uma devolução informada no portal não aumenta o estoque. O envio externo precisa ser validado após a conexão dos canais.</p></div></article>
 <article className="panel delivery-card"><span className="delivery-icon"><ScanLine/></span><div><div className="chip-row"><h3>Rotina completa e piloto</h3><span className="badge neutral">A implementar</span></div><p>Fotos e etiquetas, leitura de códigos, lotes e números de série, perdas, descontos com aprovação, importação de planilhas, equipe com permissões, conciliação, relatórios avançados e cópias com restauração. Piloto com poucas peças e parceiros antes de ampliar.</p><strong>Critério de aceite</strong><p>Validar a rotina com a equipe, revisar a experiência no celular e no computador e testar os módulos adicionais antes de ampliar a operação.</p></div></article></div>
 <div className="scope-grid two"><article className="panel scope-module"><h3>Decisões antes do uso real</h3><ul>{['Nome e responsáveis pela assistência','Estoque inicial conferido e origem dos cadastros','Valor combinado: custo, reposição ou venda','Prazos, limites, condições e responsáveis por exceções','Canal de WhatsApp, e-mail e contatos autorizados','Equipe, níveis de acesso e frequência das cópias'].map(t=><li key={t}><Check size={15}/>{t}</li>)}</ul></article><article className="panel scope-module"><h3>Fora desta primeira entrega</h3><p>Emissão fiscal, contabilidade, marketplace público, cobrança bancária automática, migração de outro sistema e operação sem internet não estão incluídos. Podem ser definidos como módulos próprios após validar a rotina principal.</p><p className="small">O plano descreve a entrega. Prazo e custo de implementação dependem dessas decisões e das integrações escolhidas.</p></article></div>
 </TabsContent></Tabs>
 </div>}
