import { z } from 'zod';
import { type State,type Piece,type Merchant,type Loan,type Event,type Settings,createLoan,settleItem,uid,stamp,today,validDate,remaining,loanCount,loanValue,balance,money,makeNoticePair,defaultSettings,dateLabel } from '../app/domain';
export type Actor={id:string;name:string;email:string;role:'owner'|'merchant';merchantId?:string};
export class AppError extends Error{status:number;constructor(message:string,status=400){super(message);this.status=status}}
const id=z.string().min(1).max(100);const note=z.string().trim().min(3,'Informe um motivo com pelo menos 3 caracteres.').max(1500);const short=z.string().trim().min(1).max(200);const qty=z.number().int().min(1).max(99999);const cents=z.number().int().min(1).max(100000000);const date=z.string().refine(validDate,'Informe uma data válida.');
const pieceSchema=z.object({id:id.optional(),name:short,sku:z.string().trim().min(1).max(40).transform(s=>s.toUpperCase()),category:short,compatible:short,quality:short,location:short,available:z.number().int().min(0).max(99999),minimum:z.number().int().min(0).max(99999),cost:z.number().int().min(0).max(100000000),value:cents});
const merchantSchema=z.object({id:id.optional(),name:short,contact:short,email:z.union([z.string().trim().email().max(150),z.literal('')]).transform(s=>s.toLowerCase()),phone:z.string().trim().max(30),city:short,limit:cents,active:z.boolean(),portalEnabled:z.boolean().optional()});
const settingsSchema=z.object({name:short,contact:z.string().trim().max(100),phone:z.string().trim().max(30),email:z.union([z.string().trim().email().max(150),z.literal('')]),city:z.string().trim().max(100),before:z.boolean(),due:z.boolean(),late:z.boolean(),hour:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/)});
const commandsSchema=z.discriminatedUnion('kind',[
 z.object({kind:z.literal('piece.save'),piece:pieceSchema}),
 z.object({kind:z.literal('merchant.save'),merchant:merchantSchema}),
 z.object({kind:z.literal('stock.move'),pieceId:id,quantity:z.number().int().min(0).max(99999),action:z.enum(['receive','count','release','discard']),reason:note}),
 z.object({kind:z.literal('loan.create'),merchantId:id,due:date,items:z.record(z.number().int().min(0).max(99999)).refine(v=>Object.keys(v).length<=100),notes:z.string().trim().max(1500)}),
 z.object({kind:z.literal('loan.settle'),loanId:id,productId:id,quantity:qty,action:z.enum(['return','quarantine','sale'])}),
 z.object({kind:z.literal('payment.record'),receivableId:id,amount:cents,reference:note}),
 z.object({kind:z.literal('payment.reverse'),paymentId:id,reason:note}),
 z.object({kind:z.literal('notices.read'),noticeId:id.optional()}),
 z.object({kind:z.literal('notices.remind'),loanId:id}),
 z.object({kind:z.literal('notices.check')}),
 z.object({kind:z.literal('settings.save'),settings:settingsSchema}),
 z.object({kind:z.literal('portal.acknowledge'),loanId:id}),
 z.object({kind:z.literal('portal.dispute'),loanId:id,reason:note}),
 z.object({kind:z.literal('portal.extend'),loanId:id,date:date,reason:note}),
 z.object({kind:z.literal('portal.return'),loanId:id,reason:note}),
 z.object({kind:z.literal('portal.read'),noticeId:id.optional()}),
 z.object({kind:z.literal('loan.extension'),loanId:id,requestId:id,approve:z.boolean(),reason:note}),
 z.object({kind:z.literal('loan.resolve'),loanId:id,reason:note})
]);
export type Command=z.infer<typeof commandsSchema>;
export type MutationResult={state:State;result:Record<string,string|number|boolean>};
const move=(s:State,title:string,description:string)=>{s.movements.unshift({id:uid('mov'),title,description,at:stamp()})};
const log=(l:Loan,title:string,description:string)=>{l.events.push({id:uid('evento'),title,description,at:stamp()})};
const notify=(s:State,l:Loan,title:string,extra:string)=>{s.notices.unshift(...makeNoticePair(s,l,title,extra))};
function getLoan(s:State,id:string,actor:Actor){const l=s.loans.find(x=>x.id===id);if(!l||actor.role==='merchant'&&l.merchantId!==actor.merchantId)throw new AppError('Empréstimo não encontrado.',404);return l}
export function applyCommand(before:State,input:unknown,actor:Actor):MutationResult{
 const parsed=commandsSchema.safeParse(input);if(!parsed.success)throw new AppError(parsed.error.issues[0]?.message||'Dados inválidos.');const c=parsed.data;
 if(c.kind.startsWith('portal.')?actor.role!=='merchant':actor.role!=='owner')throw new AppError('Seu acesso não permite esta operação.',403);
 let s=structuredClone(before);const result:Record<string,string|number|boolean>={};
 const oldEvents=new Set([...before.movements,...before.loans.flatMap(l=>l.events)].map(e=>e.id));
 const merchant=(id:string)=>{const m=s.merchants.find(m=>m.id===id);if(!m)throw new AppError('Lojista não encontrado.',404);return m};
 switch(c.kind){
 case 'piece.save':{const p=c.piece;const old=p.id?s.pieces.find(x=>x.id===p.id):undefined;if(p.id&&!old)throw new AppError('Peça não encontrada. Atualize o cadastro.',404);if(s.pieces.some(x=>x.sku.toUpperCase()===p.sku&&x.id!==p.id))throw new AppError('Este SKU já está cadastrado.',409);const saved:Piece={...p,id:old?.id||uid('p'),available:old?.available??p.available,quarantine:old?.quarantine||0};s.pieces=old?s.pieces.map(x=>x.id===old.id?saved:x):[saved,...s.pieces];move(s,old?'Cadastro de peça atualizado':'Peça cadastrada',old?`${saved.sku} · ${saved.name}. Alterações: ${Object.keys(p).filter(k=>!['id','available'].includes(k)&&JSON.stringify(old[k as keyof Piece])!==JSON.stringify(p[k as keyof typeof p])).join(', ')||'conferência do cadastro'}.`:`${saved.name} · ${saved.sku} · ${saved.available} unidades iniciais conferidas`);result.id=saved.id;break;}
 case 'merchant.save':{const m=c.merchant;const old=m.id?s.merchants.find(x=>x.id===m.id):undefined;if(m.id&&!old)throw new AppError('Lojista não encontrado.',404);if(s.merchants.some(x=>x.name.toLocaleLowerCase('pt-BR')===m.name.toLocaleLowerCase('pt-BR')&&x.id!==m.id))throw new AppError('Este lojista já está cadastrado.',409);if(m.portalEnabled&&!m.email)throw new AppError('Informe o e-mail do lojista para habilitar o portal.');if(m.portalEnabled&&s.merchants.some(x=>x.id!==m.id&&x.portalEnabled&&x.email.toLowerCase()===m.email))throw new AppError('Este e-mail já está associado a outro lojista.');if(m.portalEnabled&&m.email===actor.email.toLowerCase())throw new AppError('Use o e-mail do lojista. Seu acesso de gestão é separado do portal.');const saved:Merchant={...m,id:old?.id||uid('m'),color:old?.color||['mint','purple','blue','peach'][s.merchants.length%4],portalEnabled:!!m.portalEnabled};s.merchants=old?s.merchants.map(x=>x.id===old.id?saved:x):[...s.merchants,saved];move(s,old?'Lojista atualizado':'Lojista cadastrado',`${saved.name} · Responsável: ${saved.contact} · Limite ${money(saved.limit)} · ${saved.active?'Retiradas permitidas':'Novas retiradas bloqueadas'}`);result.id=saved.id;break;}
 case 'stock.move':{const p=s.pieces.find(x=>x.id===c.pieceId);if(!p)throw new AppError('Peça não encontrada.',404);const prior={available:p.available,quarantine:p.quarantine};if(c.action!=='count'&&c.quantity<1)throw new AppError('Informe pelo menos uma unidade.');if((c.action==='release'||c.action==='discard')&&c.quantity>p.quarantine)throw new AppError('A quantidade excede o saldo em quarentena.');if(c.action==='receive')p.available+=c.quantity;if(c.action==='count')p.available=c.quantity;if(c.action==='release'){p.quarantine-=c.quantity;p.available+=c.quantity}if(c.action==='discard')p.quarantine-=c.quantity;move(s,{receive:'Entrada de peças',count:'Inventário físico conferido',release:'Peça liberada após teste',discard:'Baixa de peça avariada'}[c.action],`${p.name} · Disponível: ${prior.available} → ${p.available}; quarentena: ${prior.quarantine} → ${p.quarantine}. Motivo: ${c.reason}`);break;}
 case 'loan.create':{try{const r=createLoan(s,c.merchantId,c.due,c.items,c.notes);s=r.state;result.id=r.loan.id}catch(e){throw new AppError((e as Error).message)}break;}
 case 'loan.settle':{getLoan(s,c.loanId,actor);try{s=settleItem(s,c.loanId,c.productId,c.quantity,c.action)}catch(e){throw new AppError((e as Error).message)}break;}
 case 'payment.record':{const r=s.receivables.find(x=>x.id===c.receivableId);if(!r)throw new AppError('Conta não encontrada.',404);if(c.amount>balance(r))throw new AppError('O valor informado excede o saldo a receber.');r.paidAmount=(r.paidAmount??(r.paid?r.amount:0))+c.amount;r.paid=r.paidAmount===r.amount;const p={id:uid('pagamento'),receivableId:r.id,amount:c.amount,reference:c.reference,at:stamp(),actorName:actor.name};s.payments=[p,...(s.payments||[])];const l=getLoan(s,r.loanId,actor);log(l,'Pagamento registrado',`${money(c.amount)} · ${c.reference}. Saldo desta conta: ${money(balance(r))}.`);move(s,'Pagamento registrado',`${merchant(r.merchantId).name} · ${money(c.amount)} · ${c.reference}`);notify(s,l,r.paid?'Conta quitada':'Pagamento parcial registrado',`${money(c.amount)} recebido. Saldo desta conta: ${money(balance(r))}. ${c.reference}`);result.id=p.id;break;}
 case 'payment.reverse':{const p=s.payments?.find(x=>x.id===c.paymentId);if(!p||p.amount<=0)throw new AppError('Pagamento não encontrado.',404);if(s.payments?.some(x=>x.reversalOf===p.id))throw new AppError('Este pagamento já foi estornado.');const r=s.receivables.find(x=>x.id===p.receivableId)!;const paid=r.paidAmount??(r.paid?r.amount:0);if(paid<p.amount)throw new AppError('O saldo não permite este estorno.');r.paidAmount=paid-p.amount;r.paid=false;s.payments!.unshift({id:uid('estorno'),receivableId:r.id,amount:-p.amount,reference:c.reason,reversalOf:p.id,at:stamp(),actorName:actor.name});const l=getLoan(s,r.loanId,actor);log(l,'Estorno de registro de pagamento',`${money(p.amount)} voltou ao saldo a receber. ${c.reason}`);move(s,'Pagamento estornado',`${l.id} · ${money(p.amount)} · ${c.reason}`);notify(s,l,'Registro de pagamento estornado',`${money(p.amount)} voltou ao saldo a receber. ${c.reason}`);break;}
 case 'notices.read':{s.notices=s.notices.map(n=>!c.noticeId||n.id===c.noticeId?{...n,read:true}:n);break;}
 case 'notices.remind':{const l=getLoan(s,c.loanId,actor);if(!loanCount(l))throw new AppError('Este empréstimo já foi encerrado.');const recent=s.notices.find(n=>n.loanId===l.id&&n.title==='Lembrete de devolução'&&Date.now()-Date.parse(n.at)<60000);if(recent)throw new AppError('Um lembrete já foi criado há menos de um minuto.');notify(s,l,'Lembrete de devolução',`Saldo pendente: ${loanCount(l)} peça(s). Prazo: ${dateLabel(l.due)}.`);move(s,'Lembrete registrado',`${l.id} · ${merchant(l.merchantId).name}`);break;}
 case 'notices.check':{let count=0;const d=today();const settings=s.settings||defaultSettings;for(const l of s.loans.filter(l=>loanCount(l)>0)){const diff=Math.round((Date.parse(l.due+'T12:00:00Z')-Date.parse(d+'T12:00:00Z'))/86400000);const title=diff===1&&settings.before?'Devolução prevista para amanhã':diff===0&&settings.due?'Devolução prevista para hoje':diff<0&&settings.late&&Math.abs(diff)%2===1?'Prazo de devolução vencido':null;if(!title)continue;const eventKey=`due:${l.id}:${l.due}:${d}`;if(s.notices.some(n=>n.eventKey===eventKey))continue;s.notices.unshift(...makeNoticePair(s,l,title,'Confira as quantidades pendentes e entre em contato se precisar combinar a devolução.').map(n=>({...n,eventKey})));count++;}result.count=count;break;}
 case 'settings.save':{s.settings=c.settings;move(s,'Dados da assistência atualizados',`${c.settings.name} · Contato: ${c.settings.contact||'não informado'}. Preferências de avisos salvas.`);break;}
 case 'portal.acknowledge':{const l=getLoan(s,c.loanId,actor);if(!loanCount(l))throw new AppError('Este empréstimo está encerrado.');if(l.acknowledged){result.alreadyAcknowledged=true;break}if(l.dispute)throw new AppError('Aguarde a assistência resolver a divergência antes de confirmar.');l.acknowledged=true;l.acknowledgedBy=actor.name;l.acknowledgedAt=stamp();log(l,'Recebimento confirmado pelo lojista',`${actor.name} confirmou os itens e as condições do comprovante.`);notify(s,l,'Recebimento confirmado',`Confirmado por ${actor.name} em ${stamp()}.`);break;}
 case 'portal.dispute':{const l=getLoan(s,c.loanId,actor);if(!loanCount(l))throw new AppError('Este empréstimo está encerrado.');l.dispute=c.reason;log(l,'Divergência comunicada pelo lojista',c.reason);notify(s,l,'Divergência na retirada',c.reason);break;}
 case 'portal.extend':{const l=getLoan(s,c.loanId,actor);if(!loanCount(l))throw new AppError('Este empréstimo está encerrado.');if(c.date<=l.due||c.date<today())throw new AppError('A nova data deve ser posterior ao prazo atual e não pode estar no passado.');if(l.requests?.some(r=>r.status==='pending'))throw new AppError('Já existe um pedido de prazo aguardando resposta.');l.requests=[...(l.requests||[]),{id:uid('prazo'),date:c.date,reason:c.reason,status:'pending',at:stamp()}];log(l,'Prorrogação solicitada',`Nova data solicitada: ${c.date}. ${c.reason}`);notify(s,l,'Pedido de prorrogação',`Data solicitada: ${dateLabel(c.date)}. O prazo atual continua valendo até a aprovação. ${c.reason}`);break;}
 case 'portal.return':{const l=getLoan(s,c.loanId,actor);if(!loanCount(l))throw new AppError('Este empréstimo está encerrado.');log(l,'Lojista avisou sobre a devolução',c.reason);notify(s,l,'Devolução informada pelo lojista',`${c.reason}. Entrada no estoque depende da conferência da assistência.`);break;}
 case 'portal.read':{s.notices=s.notices.map(n=>n.merchantId===actor.merchantId&&n.audience==='Lojista'&&(!c.noticeId||c.noticeId===n.id)?{...n,portalRead:true}:n);break;}
 case 'loan.extension':{const l=getLoan(s,c.loanId,actor);const r=l.requests?.find(r=>r.id===c.requestId);if(!r||r.status!=='pending')throw new AppError('Pedido de prazo não encontrado ou já respondido.');if(!loanCount(l))throw new AppError('O empréstimo está encerrado.');if(c.approve&&r.date<today())throw new AppError('A data solicitada já passou. Peça uma nova previsão ao lojista.');const old=l.due;r.status=c.approve?'approved':'declined';if(c.approve)l.due=r.date;log(l,c.approve?'Prorrogação aprovada':'Prorrogação recusada',`Prazo anterior: ${old}; prazo vigente: ${l.due}. ${c.reason}`);notify(s,l,c.approve?'Novo prazo aprovado':'Pedido de prazo respondido',`Prazo vigente: ${dateLabel(l.due)}. ${c.reason}`);break;}
 case 'loan.resolve':{const l=getLoan(s,c.loanId,actor);if(!l.dispute)throw new AppError('Não há divergência aberta.');log(l,'Divergência resolvida pela assistência',`Relato original: ${l.dispute}. Solução: ${c.reason}`);l.dispute=undefined;notify(s,l,'Divergência resolvida',c.reason);break;}
 }
 for(const e of [...s.movements,...s.loans.flatMap(l=>l.events)])if(!oldEvents.has(e.id)){e.actorId=actor.id;e.actorName=actor.name}
 for(const p of s.pieces)if(!Number.isSafeInteger(p.available)||p.available<0||p.quarantine<0)throw new AppError('A operação produziria um saldo inválido.');
 return {state:s,result};
}
