import { sql } from 'drizzle-orm';
import { pgTable, text, integer, uuid, timestamp, date, index, uniqueIndex, check } from 'drizzle-orm/pg-core';
export const workspaces=pgTable('workspaces',{id:text('id').primaryKey(),ownerId:uuid('owner_id').notNull(),ownerEmail:text('owner_email').notNull(),revision:integer('revision').notNull().default(0),lastCommand:text('last_command').notNull().default(''),settings:text('settings').notNull(),createdAt:timestamp('created_at',{withTimezone:true,mode:'string'}).notNull()}).enableRLS();
export const pieces=pgTable('pieces',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),sku:text('sku').notNull(),available:integer('available').notNull(),quarantine:integer('quarantine').notNull(),payload:text('payload').notNull()},t=>[uniqueIndex('idx_pieces_workspace_sku').on(t.workspaceId,t.sku),check('piece_available_nonnegative',sql`${t.available} >= 0`),check('piece_quarantine_nonnegative',sql`${t.quarantine} >= 0`)]).enableRLS();
export const merchants=pgTable('merchants',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),nameKey:text('name_key').notNull(),email:text('email').notNull(),portalEnabled:integer('portal_enabled').notNull().default(0),portalUserId:uuid('portal_user_id'),payload:text('payload').notNull()},t=>[uniqueIndex('idx_merchants_workspace_name').on(t.workspaceId,t.nameKey),uniqueIndex('idx_merchants_portal_email').on(t.workspaceId,t.email).where(sql`${t.portalEnabled} = 1`),check('merchant_portal_flag',sql`${t.portalEnabled} in (0,1)`)]).enableRLS();
export const loans=pgTable('loans',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),merchantId:text('merchant_id').notNull().references(()=>merchants.id),due:date('due',{mode:'string'}).notNull(),payload:text('payload').notNull()},t=>[index('idx_loans_workspace_merchant').on(t.workspaceId,t.merchantId),index('idx_loans_workspace_due').on(t.workspaceId,t.due),index('idx_loans_merchant').on(t.merchantId)]).enableRLS();
export const loanItems=pgTable('loan_items',{id:text('id').primaryKey(),loanId:text('loan_id').notNull().references(()=>loans.id),productId:text('product_id').notNull().references(()=>pieces.id),quantity:integer('quantity').notNull(),returned:integer('returned').notNull(),sold:integer('sold').notNull(),value:integer('value').notNull(),payload:text('payload').notNull()},t=>[uniqueIndex('idx_loan_items_loan_product').on(t.loanId,t.productId),check('item_quantity_balance',sql`${t.quantity} > 0 AND ${t.returned} >= 0 AND ${t.sold} >= 0 AND ${t.returned} + ${t.sold} <= ${t.quantity}`),check('item_value_positive',sql`${t.value} > 0`),index('idx_loan_items_product').on(t.productId)]).enableRLS();
export const events=pgTable('loan_events',{id:text('id').primaryKey(),loanId:text('loan_id').notNull().references(()=>loans.id),at:timestamp('at',{withTimezone:true,mode:'string'}).notNull(),payload:text('payload').notNull()},t=>[index('idx_loan_events_loan_at').on(t.loanId,t.at)]).enableRLS();
export const receivables=pgTable('receivables',{createdAt:timestamp('created_at',{withTimezone:true,mode:'string'}).notNull(),id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),loanId:text('loan_id').notNull().references(()=>loans.id),merchantId:text('merchant_id').notNull().references(()=>merchants.id),amount:integer('amount').notNull(),paidAmount:integer('paid_amount').notNull().default(0),payload:text('payload').notNull()},t=>[index('idx_receivables_workspace_merchant').on(t.workspaceId,t.merchantId),index('idx_receivables_loan').on(t.loanId),index('idx_receivables_merchant').on(t.merchantId),check('receivable_balance',sql`${t.amount} > 0 AND ${t.paidAmount} >= 0 AND ${t.paidAmount} <= ${t.amount}`)]).enableRLS();
export const payments=pgTable('payments',{createdAt:timestamp('created_at',{withTimezone:true,mode:'string'}).notNull(),id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),receivableId:text('receivable_id').notNull().references(()=>receivables.id),amount:integer('amount').notNull(),payload:text('payload').notNull()},t=>[index('idx_payments_workspace_receivable').on(t.workspaceId,t.receivableId),index('idx_payments_receivable').on(t.receivableId),check('payment_nonzero',sql`${t.amount} != 0`)]).enableRLS();
export const notices=pgTable('notices',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),loanId:text('loan_id').notNull().references(()=>loans.id),merchantId:text('merchant_id').notNull().references(()=>merchants.id),audience:text('audience').notNull(),at:timestamp('at',{withTimezone:true,mode:'string'}).notNull(),payload:text('payload').notNull()},t=>[index('idx_notices_workspace_recipient').on(t.workspaceId,t.merchantId,t.audience,t.at),index('idx_notices_loan').on(t.loanId),index('idx_notices_merchant').on(t.merchantId)]).enableRLS();
export const movements=pgTable('movements',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),at:timestamp('at',{withTimezone:true,mode:'string'}).notNull(),payload:text('payload').notNull()},t=>[index('idx_movements_workspace_at').on(t.workspaceId,t.at)]).enableRLS();
export const commands=pgTable('commands',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),fingerprint:text('fingerprint').notNull(),actorId:uuid('actor_id').notNull(),actorName:text('actor_name').notNull(),kind:text('kind').notNull(),revision:integer('revision').notNull(),result:text('result').notNull(),at:timestamp('at',{withTimezone:true,mode:'string'}).notNull(),guard:integer('guard').notNull()},t=>[index('idx_commands_workspace_at').on(t.workspaceId,t.at),check('command_revision_guard',sql`${t.guard} = 1`)]).enableRLS();
export const messagingConnections=pgTable('messaging_connections',{workspaceId:text('workspace_id').primaryKey().references(()=>workspaces.id),encryptedKey:text('encrypted_key').notNull(),sender:text('sender').notNull(),provider:text('provider').notNull().default('resend'),endpoint:text('endpoint'),quotaRemaining:integer('quota_remaining'),enabled:integer('enabled').notNull().default(0),revision:integer('revision').notNull().default(1),verifiedAt:timestamp('verified_at',{withTimezone:true,mode:'string'}),updatedAt:timestamp('updated_at',{withTimezone:true,mode:'string'}).notNull()}).enableRLS();
export const emailOutbox=pgTable('email_outbox',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),noticeId:text('notice_id').references(()=>notices.id),loanId:text('loan_id').notNull(),audience:text('audience').notNull(),recipient:text('recipient').notNull(),recipientName:text('recipient_name').notNull(),phone:text('phone').notNull(),status:text('status').notNull(),subject:text('subject').notNull(),body:text('body').notNull(),requestPayload:text('request_payload'),connectionRevision:integer('connection_revision'),attempts:integer('attempts').notNull().default(0),providerId:text('provider_id'),provider:text('provider'),error:text('error'),firstAttemptAt:timestamp('first_attempt_at',{withTimezone:true,mode:'string'}),nextAttemptAt:timestamp('next_attempt_at',{withTimezone:true,mode:'string'}),leaseToken:text('lease_token'),leaseUntil:timestamp('lease_until',{withTimezone:true,mode:'string'}),createdAt:timestamp('created_at',{withTimezone:true,mode:'string'}).notNull(),updatedAt:timestamp('updated_at',{withTimezone:true,mode:'string'}).notNull(),checkedAt:timestamp('checked_at',{withTimezone:true,mode:'string'}),whatsappAt:timestamp('whatsapp_at',{withTimezone:true,mode:'string'})},t=>[uniqueIndex('idx_email_outbox_notice').on(t.workspaceId,t.noticeId),index('idx_email_outbox_queue').on(t.workspaceId,t.status,t.nextAttemptAt),index('idx_email_outbox_recipient').on(t.workspaceId,t.recipient),index('idx_email_outbox_notice_id').on(t.noticeId)]).enableRLS();

export const gmailSetups=pgTable('gmail_setups',{workspaceId:text('workspace_id').primaryKey().references(()=>workspaces.id),sender:text('sender').notNull(),encryptedSecret:text('encrypted_secret').notNull(),createdAt:timestamp('created_at',{withTimezone:true,mode:'string'}).notNull()}).enableRLS();
