import { sql } from 'drizzle-orm';
import { sqliteTable, text, integer, index, uniqueIndex, check } from 'drizzle-orm/sqlite-core';
export const workspaces=sqliteTable('workspaces',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),ownerEmail:text('owner_email').notNull(),revision:integer('revision').notNull().default(0),lastCommand:text('last_command').notNull().default(''),settings:text('settings').notNull(),createdAt:text('created_at').notNull()});
export const pieces=sqliteTable('pieces',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),sku:text('sku').notNull(),available:integer('available').notNull(),quarantine:integer('quarantine').notNull(),payload:text('payload').notNull()},t=>[uniqueIndex('idx_pieces_workspace_sku').on(t.workspaceId,t.sku),check('piece_available_nonnegative',sql`${t.available} >= 0`),check('piece_quarantine_nonnegative',sql`${t.quarantine} >= 0`)]);
export const merchants=sqliteTable('merchants',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),nameKey:text('name_key').notNull(),email:text('email').notNull(),portalEnabled:integer('portal_enabled').notNull().default(0),portalUserId:text('portal_user_id'),payload:text('payload').notNull()},t=>[uniqueIndex('idx_merchants_workspace_name').on(t.workspaceId,t.nameKey),index('idx_merchants_portal_email').on(t.workspaceId,t.email)]);
export const loans=sqliteTable('loans',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),merchantId:text('merchant_id').notNull().references(()=>merchants.id),due:text('due').notNull(),payload:text('payload').notNull()},t=>[index('idx_loans_workspace_merchant').on(t.workspaceId,t.merchantId),index('idx_loans_workspace_due').on(t.workspaceId,t.due)]);
export const loanItems=sqliteTable('loan_items',{id:text('id').primaryKey(),loanId:text('loan_id').notNull().references(()=>loans.id),productId:text('product_id').notNull().references(()=>pieces.id),quantity:integer('quantity').notNull(),returned:integer('returned').notNull(),sold:integer('sold').notNull(),value:integer('value').notNull(),payload:text('payload').notNull()},t=>[uniqueIndex('idx_loan_items_loan_product').on(t.loanId,t.productId),check('item_quantity_balance',sql`${t.quantity} > 0 AND ${t.returned} >= 0 AND ${t.sold} >= 0 AND ${t.returned} + ${t.sold} <= ${t.quantity}`),check('item_value_positive',sql`${t.value} > 0`)]);
export const events=sqliteTable('loan_events',{id:text('id').primaryKey(),loanId:text('loan_id').notNull().references(()=>loans.id),at:text('at').notNull(),payload:text('payload').notNull()},t=>[index('idx_loan_events_loan_at').on(t.loanId,t.at)]);
export const receivables=sqliteTable('receivables',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),loanId:text('loan_id').notNull().references(()=>loans.id),merchantId:text('merchant_id').notNull().references(()=>merchants.id),amount:integer('amount').notNull(),paidAmount:integer('paid_amount').notNull().default(0),payload:text('payload').notNull()},t=>[index('idx_receivables_workspace_merchant').on(t.workspaceId,t.merchantId),check('receivable_balance',sql`${t.amount} > 0 AND ${t.paidAmount} >= 0 AND ${t.paidAmount} <= ${t.amount}`)]);
export const payments=sqliteTable('payments',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),receivableId:text('receivable_id').notNull().references(()=>receivables.id),amount:integer('amount').notNull(),payload:text('payload').notNull()},t=>[index('idx_payments_workspace_receivable').on(t.workspaceId,t.receivableId),check('payment_nonzero',sql`${t.amount} != 0`)]);
export const notices=sqliteTable('notices',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),loanId:text('loan_id').notNull().references(()=>loans.id),merchantId:text('merchant_id').notNull().references(()=>merchants.id),audience:text('audience').notNull(),at:text('at').notNull(),payload:text('payload').notNull()},t=>[index('idx_notices_workspace_recipient').on(t.workspaceId,t.merchantId,t.audience,t.at)]);
export const movements=sqliteTable('movements',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),at:text('at').notNull(),payload:text('payload').notNull()},t=>[index('idx_movements_workspace_at').on(t.workspaceId,t.at)]);
export const commands=sqliteTable('commands',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),fingerprint:text('fingerprint').notNull(),actorId:text('actor_id').notNull(),actorName:text('actor_name').notNull(),kind:text('kind').notNull(),revision:integer('revision').notNull(),result:text('result').notNull(),at:text('at').notNull(),guard:integer('guard').notNull()},t=>[index('idx_commands_workspace_at').on(t.workspaceId,t.at),check('command_revision_guard',sql`${t.guard} = 1`)]);
export const messagingConnections=sqliteTable('messaging_connections',{workspaceId:text('workspace_id').primaryKey().references(()=>workspaces.id),encryptedKey:text('encrypted_key').notNull(),sender:text('sender').notNull(),provider:text('provider').notNull().default('resend'),endpoint:text('endpoint'),quotaRemaining:integer('quota_remaining'),enabled:integer('enabled').notNull().default(0),revision:integer('revision').notNull().default(1),verifiedAt:text('verified_at'),updatedAt:text('updated_at').notNull()});
export const emailOutbox=sqliteTable('email_outbox',{id:text('id').primaryKey(),workspaceId:text('workspace_id').notNull().references(()=>workspaces.id),noticeId:text('notice_id').references(()=>notices.id),loanId:text('loan_id').notNull(),audience:text('audience').notNull(),recipient:text('recipient').notNull(),recipientName:text('recipient_name').notNull(),phone:text('phone').notNull(),status:text('status').notNull(),subject:text('subject').notNull(),body:text('body').notNull(),requestPayload:text('request_payload'),connectionRevision:integer('connection_revision'),attempts:integer('attempts').notNull().default(0),providerId:text('provider_id'),provider:text('provider'),error:text('error'),firstAttemptAt:text('first_attempt_at'),nextAttemptAt:text('next_attempt_at'),leaseToken:text('lease_token'),leaseUntil:text('lease_until'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),checkedAt:text('checked_at'),whatsappAt:text('whatsapp_at')},t=>[uniqueIndex('idx_email_outbox_notice').on(t.workspaceId,t.noticeId),index('idx_email_outbox_queue').on(t.workspaceId,t.status,t.nextAttemptAt),index('idx_email_outbox_recipient').on(t.workspaceId,t.recipient)]);

export const gmailSetups=sqliteTable('gmail_setups',{workspaceId:text('workspace_id').primaryKey().references(()=>workspaces.id),sender:text('sender').notNull(),encryptedSecret:text('encrypted_secret').notNull(),createdAt:text('created_at').notNull()});
