import type {SqlDatabase} from '../server/database';
import assert from 'node:assert/strict';
import {D1,type Statement} from './sqlite-d1';
import {readFileSync,readdirSync,mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {Repository,portalSnapshot} from '../server/repository';
import {balance,loanCount,loanValue,merchantExposure,dayOffset} from '../app/domain';
const folder=mkdtempSync(join(tmpdir(),'elo-db-check-'));const path=join(folder,'db.sqlite');
const db=new D1(path);for(const f of readdirSync('tests/fixtures/sqlite').filter(f=>f.endsWith('.sql')).sort())db.sqlite.exec(readFileSync('tests/fixtures/sqlite/'+f,'utf8'));
let repo=new Repository(db as unknown as SqlDatabase,{id:'owner-test',email:'lopesleticia297@gmail.com'});
const owner=await repo.actor({userId:'owner-test',email:'lopesleticia297@gmail.com',displayName:'Proprietária'});
assert.equal(owner.role,'owner');assert.equal((await repo.read(owner)).state.pieces.length,0);
await assert.rejects(repo.actor({userId:'other-user',email:'outsider@example.com',displayName:'Outro usuário'}),/não está habilitado/);
let snapshot=await repo.read(owner);
async function execute(command:unknown,actor=owner){const r=await repo.execute(actor,crypto.randomUUID(),snapshot.revision,command);snapshot=r;return r}
const p=await execute({kind:'piece.save',piece:{name:'Tela de teste',sku:'TEL-TESTE',category:'Telas',compatible:'Modelo de teste',quality:'Nova',location:'Gaveta A',available:5,minimum:1,cost:5000,value:10000}});const pieceId=String(p.result.id);
const m=await execute({kind:'merchant.save',merchant:{name:'Loja de teste',contact:'Responsável de teste',email:'parceiro@example.com',phone:'',city:'Betim',limit:100000,active:true,portalEnabled:true}});const merchantId=String(m.result.id);
const m2=await execute({kind:'merchant.save',merchant:{name:'Outra loja',contact:'Outro responsável',email:'outra@example.com',phone:'',city:'Betim',limit:100000,active:true,portalEnabled:true}});const otherMerchantId=String(m2.result.id);
const partner=await repo.actor({userId:'partner-test',email:'parceiro@example.com',displayName:'Lojista'});assert.equal(partner.role,'merchant');assert.equal(partner.merchantId,merchantId);
await assert.rejects(repo.actor({userId:'wrong-bound-id',email:'parceiro@example.com',displayName:'Outra identidade'}),/outra identidade/);
const loanCommand={kind:'loan.create',merchantId,due:dayOffset(1),items:{[pieceId]:3},notes:'Peças conferidas na retirada.'};const operationId=crypto.randomUUID();const originalRevision=snapshot.revision;const loan=await repo.execute(owner,operationId,originalRevision,loanCommand);snapshot=loan;const loanId=String(loan.result.id);
assert.equal(loanId,'EMP-0001');assert.equal(snapshot.state.pieces[0].available,2);assert.equal(snapshot.state.notices.length,2);
const retry=await repo.execute(owner,operationId,originalRevision,loanCommand);assert.equal(retry.state.loans.length,1);assert.equal(retry.state.pieces[0].available,2);assert.equal(retry.revision,snapshot.revision);
await assert.rejects(repo.execute(owner,operationId,snapshot.revision,{...loanCommand,notes:'Alterada'}),/outra operação/);
await assert.rejects(execute({kind:'loan.create',merchantId,due:dayOffset(1),items:{[pieceId]:10},notes:''}),/estoque insuficiente/);
await assert.rejects(execute({kind:'portal.acknowledge',loanId},owner),/não permite/);
await assert.rejects(execute({kind:'piece.save',piece:{name:'invasão'}},partner));
await execute({kind:'portal.acknowledge',loanId},partner);assert.equal(snapshot.state.loans[0].acknowledged,true);assert.equal(snapshot.state.loans[0].acknowledgedBy,'Lojista');
await execute({kind:'portal.return',loanId,reason:'Vou devolver uma tela amanhã.'},partner);assert.equal(snapshot.state.pieces[0].available,2);assert.equal(loanCount(snapshot.state.loans[0]),3);
await execute({kind:'portal.extend',loanId,date:dayOffset(4),reason:'Preciso de mais prazo para concluir o reparo.'},partner);const request=snapshot.state.loans[0].requests![0];assert.equal(snapshot.state.loans[0].due,dayOffset(1));
await execute({kind:'loan.extension',loanId,requestId:request.id,approve:true,reason:'Novo prazo combinado com o parceiro.'});assert.equal(snapshot.state.loans[0].due,dayOffset(4));
await execute({kind:'loan.settle',loanId,productId:pieceId,quantity:1,action:'return'});assert.equal(snapshot.state.pieces[0].available,3);assert.equal(loanCount(snapshot.state.loans[0]),2);
await execute({kind:'loan.settle',loanId,productId:pieceId,quantity:1,action:'quarantine'});assert.equal(snapshot.state.pieces[0].available,3);assert.equal(snapshot.state.pieces[0].quarantine,1);
const exp=merchantExposure(snapshot.state,merchantId);await execute({kind:'loan.settle',loanId,productId:pieceId,quantity:1,action:'sale'});assert.equal(merchantExposure(snapshot.state,merchantId),exp);assert.equal(loanCount(snapshot.state.loans[0]),0);const receivableId=snapshot.state.receivables[0].id;
await assert.rejects(execute({kind:'loan.settle',loanId,productId:pieceId,quantity:1,action:'return'}),/saldo pendente/);
const pay=await execute({kind:'payment.record',receivableId,amount:4000,reference:'Pix conferido no extrato'});const paymentId=String(pay.result.id);assert.equal(balance(snapshot.state.receivables[0]),6000);assert.equal(snapshot.state.receivables[0].paid,false);assert.equal(merchantExposure(snapshot.state,merchantId),6000);
await assert.rejects(execute({kind:'payment.record',receivableId,amount:7000,reference:'Valor acima do saldo'}),/excede/);
await execute({kind:'payment.reverse',paymentId,reason:'Registro feito por engano'});assert.equal(balance(snapshot.state.receivables[0]),10000);assert.equal(snapshot.state.payments!.length,2);
await assert.rejects(execute({kind:'payment.reverse',paymentId,reason:'Segundo estorno inválido'}),/já foi estornado/);
await execute({kind:'stock.move',pieceId,action:'release',quantity:1,reason:'Peça testada e aprovada'});assert.equal(snapshot.state.pieces[0].available,4);assert.equal(snapshot.state.pieces[0].quarantine,0);
const otherLoan=await execute({kind:'loan.create',merchantId:otherMerchantId,due:dayOffset(3),items:{[pieceId]:1},notes:'Outra loja'});const otherLoanId=String(otherLoan.result.id);
await assert.rejects(execute({kind:'portal.acknowledge',loanId:otherLoanId},partner),/não encontrado/);
const portal=portalSnapshot(await repo.read(partner));assert.equal(portal.loans.length,1);assert.equal(portal.loans[0].id,loanId);assert.ok(portal.notices.every(n=>n.merchantId===merchantId&&n.audience==='Lojista'));assert.equal('pieces' in portal,false);assert.equal('movements' in portal,false);assert.equal('ownerId' in portal,false);
await execute({kind:'stock.move',pieceId,action:'count',quantity:1,reason:'Contagem física da unidade disponível'});
const revision=snapshot.revision;const raceCommand={kind:'loan.create',merchantId,due:dayOffset(2),items:{[pieceId]:1},notes:'Disputa pela última peça'};
const race=await Promise.allSettled([repo.execute(owner,crypto.randomUUID(),revision,raceCommand),repo.execute(owner,crypto.randomUUID(),revision,raceCommand)]);
assert.equal(race.filter(r=>r.status==='fulfilled').length,1);assert.equal(race.filter(r=>r.status==='rejected').length,1);snapshot=await repo.read(owner);assert.equal(snapshot.state.pieces[0].available,0);
await assert.rejects(db.prepare('UPDATE pieces SET available=-1 WHERE id=?').bind(pieceId).run(),/CHECK/);
// A mid-operation database failure must roll back inventory, audit and command receipt together.
const beforeFailure=JSON.stringify(snapshot.state);const beforeRevision=snapshot.revision;const failureId=crypto.randomUUID();db.failNextBatchAt=2;
// The next read uses batch as well: arrange the failure specifically on the mutation batch.
const originalBatch=db.batch.bind(db);db.failNextBatchAt=null;db.batch=async(statements:Statement[])=>{if(statements[0].sql.startsWith('UPDATE workspaces'))db.failNextBatchAt=2;return originalBatch(statements)};
await assert.rejects(repo.execute(owner,failureId,beforeRevision,{kind:'stock.move',pieceId,action:'receive',quantity:2,reason:'Entrada que deve falhar integralmente'}),/injected/);
db.batch=originalBatch;snapshot=await repo.read(owner);assert.equal(JSON.stringify(snapshot.state),beforeFailure);assert.equal(snapshot.revision,beforeRevision);
assert.equal(await db.prepare('SELECT id FROM commands WHERE id=?').bind(failureId).first(),null);
// Persist across a new SQLite connection and repository instance.
db.sqlite.close();const reopened=new D1(path);repo=new Repository(reopened as unknown as SqlDatabase,{id:'owner-test',email:'lopesleticia297@gmail.com'});const reloaded=await repo.read(owner);assert.deepEqual(reloaded.state,snapshot.state);assert.equal(reloaded.revision,snapshot.revision);assert.equal(reloaded.state.movements.every(m=>!!m.actorName),true);
const borrowedValue=loanValue(reloaded.state.loans.find(l=>l.id===otherLoanId)!);snapshot=reloaded;const part=snapshot.state.pieces[0];await execute({kind:'piece.save',piece:{...part,value:20000}});assert.equal(loanValue(snapshot.state.loans.find(l=>l.id===otherLoanId)!),borrowedValue);
reopened.sqlite.close();rmSync(folder,{recursive:true,force:true});
console.log('OK: durable reload, empty initial stock, owner bootstrap, partner identity binding, portal isolation, server authorization, immutable prices, atomic last-unit race, rollback, idempotency, partial return, quarantine, sales, partial payments, reversal and extension approval.');
