import assert from 'node:assert/strict';
import { seedState, createLoan, settleItem, dayOffset, loanCount, loanValue, merchantExposure, remaining } from '../app/domain.ts';
const base=seedState();
const original=JSON.stringify(base);
const result=createLoan(base,'m1',dayOffset(3),{p1:3,p2:2},'Teste de conferência');
assert.equal(JSON.stringify(base),original,'Creating a loan must preserve previous state.');
assert.equal(result.state.pieces.find(p=>p.id==='p1').available,9);
assert.equal(loanCount(result.loan),5);
assert.equal(result.state.notices.length,base.notices.length+2);
assert.deepEqual(result.state.notices.slice(0,2).map(n=>n.audience),['Você','Lojista']);
assert.equal(result.state.notices[0].body.includes('TEL-013-OLED'),true);
assert.throws(()=>createLoan(base,'m1',dayOffset(3),{p1:13},''),/estoque insuficiente/);
assert.throws(()=>createLoan(base,'m1',dayOffset(-1),{p1:1},''),/prazo/);
assert.throws(()=>createLoan(base,'m1',dayOffset(3),{p1:1.5},''),/Quantidade/);
let s=settleItem(result.state,result.loan.id,'p1',1,'return');
assert.equal(s.pieces.find(p=>p.id==='p1').available,10);
assert.equal(loanCount(s.loans.find(l=>l.id===result.loan.id)),4);
s=settleItem(s,result.loan.id,'p1',1,'quarantine');
assert.equal(s.pieces.find(p=>p.id==='p1').available,10);
assert.equal(s.pieces.find(p=>p.id==='p1').quarantine,1);
const exposure=merchantExposure(s,'m1');
s=settleItem(s,result.loan.id,'p1',1,'sale');
assert.equal(s.receivables[0].paid,false);
assert.equal(s.receivables[0].amount,29000);
assert.equal(merchantExposure(s,'m1'),exposure,'Converting to sale must not free the partner limit before payment.');
assert.throws(()=>settleItem(s,result.loan.id,'p1',1,'return'),/saldo pendente/);
assert.throws(()=>settleItem(s,result.loan.id,'p2',-1,'return'),/saldo pendente/);
assert.throws(()=>createLoan({...base,merchants:base.merchants.map(m=>m.id==='m1'?{...m,active:false}:m)},'m1',dayOffset(3),{p1:1},''),/ativo/);
assert.throws(()=>createLoan({...base,merchants:base.merchants.map(m=>m.id==='m1'?{...m,limit:100}:m)},'m1',dayOffset(3),{p1:1},''),/limite/);
const snapshot=loanValue(s.loans.find(l=>l.id===result.loan.id));
s={...s,pieces:s.pieces.map(p=>({...p,value:999999}))};
assert.equal(loanValue(s.loans.find(l=>l.id===result.loan.id)),snapshot,'Catalog edits must not rewrite loan values.');
for(const l of s.loans)for(const i of l.items){assert.equal(i.quantity,i.returned+i.sold+remaining(i));assert.ok(remaining(i)>=0)}
console.log('OK: stock availability, limit enforcement, two recipient previews, partial return, quarantine, sale debt, immutable price and quantity conservation.');
